// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY_gmxjbEkCSbyg_gMyq6K_YVd_nP8t7E',
    appId: '1:561843030511:web:7dde1793d4b8edcd060e1a',
    messagingSenderId: '561843030511',
    projectId: 'mini-social-app-c171e',
    authDomain: 'mini-social-app-c171e.firebaseapp.com',
    storageBucket: 'mini-social-app-c171e.appspot.com',
    measurementId: 'G-MYPSFJBGW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC_RZNyQSUiD8FUTMcsN5gcG-DmQ1iwAo',
    appId: '1:561843030511:android:0aec67da381f787f060e1a',
    messagingSenderId: '561843030511',
    projectId: 'mini-social-app-c171e',
    storageBucket: 'mini-social-app-c171e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUTVG_QiekNFhcjaxr1nnyEN2FBmqJwJw',
    appId: '1:561843030511:ios:66ff8fd429d3db5b060e1a',
    messagingSenderId: '561843030511',
    projectId: 'mini-social-app-c171e',
    storageBucket: 'mini-social-app-c171e.appspot.com',
    iosBundleId: 'com.example.firebaseSocialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUTVG_QiekNFhcjaxr1nnyEN2FBmqJwJw',
    appId: '1:561843030511:ios:a273b4bd76eca097060e1a',
    messagingSenderId: '561843030511',
    projectId: 'mini-social-app-c171e',
    storageBucket: 'mini-social-app-c171e.appspot.com',
    iosBundleId: 'com.example.firebaseSocialApp.RunnerTests',
  );
}
